name: flutter_qr_app
packages:
  - apps/*
  - packages/auth_biometrics
  - packages/qr_scanner
scripts:
  analyze:
    exec: dart analyze .
  test:selective_unit_test:
    exec: flutter test
    dir-exists: "test"
    fail-fast: true
    description: Run selective unit tests

  test:all_unit_tests:
    exec: flutter test
    no-select: true
    description: Run all unit testsAdditionally, you can incorporate commands for analysis and code coverage. Melos offers a GUI interface for seamless execution without terminal input.
