name: flutter_qr_app
version: 0.0.1+1
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  firebase_core: 3.12.0
  flutter:
    sdk: flutter
  hydrated_bloc: 10.0.0
  pigeon: ^24.2.1
  freezed: ^2.5.8
  flutter_bloc: ^9.0.0
  get_it: 8.0.3
  injectable: ^2.5.0
  path_provider: ^2.1.5

dev_dependencies:
  melos: ^6.3.2
  bloc_test: 10.0.0
  build_runner: 2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

  qr_scanner:
    path: packages/qr_scanner
  auth_biometrics:
    path: packages/auth_biometrics
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true # Add this line
