name: flutter_qr_app
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  firebase_core: 3.12.0
  flutter:
    sdk: flutter
  hydrated_bloc: 10.0.0
  pigeon: ^24.2.1

dev_dependencies:
  melos: ^6.3.2

  qr_scanner:
    path: packages/qr_scanner
  auth_biometrics:
    path: packages/auth_biometrics
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true # Add this line
