// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqA-MlCupJhsm8TNaMOXa2SZfQgOZ_Abg',
    appId: '1:649379723598:web:dc5f2c0969c7047657461f',
    messagingSenderId: '649379723598',
    projectId: 'seek-71e30',
    authDomain: 'seek-71e30.firebaseapp.com',
    storageBucket: 'seek-71e30.firebasestorage.app',
    measurementId: 'G-Y1EJ32YWH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGowjUF-UQPhZsxrkvyjwqvSvsDXcTD1A',
    appId: '1:649379723598:android:218e18f913c5577b57461f',
    messagingSenderId: '649379723598',
    projectId: 'seek-71e30',
    storageBucket: 'seek-71e30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7G0kr6CwGMAfns-LStZMJdx-8HgeBRU',
    appId: '1:649379723598:ios:559a73099a7ca71d57461f',
    messagingSenderId: '649379723598',
    projectId: 'seek-71e30',
    storageBucket: 'seek-71e30.firebasestorage.app',
    iosBundleId: 'py.com.seek',
  );
}
