// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PGNSaveQrScan;
@class PGNReadFileMessage;
@class PGNFileResponse;

@interface PGNSaveQrScan : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithQrData:(NSString *)qrData
    date:(NSString *)date;
@property(nonatomic, copy) NSString * qrData;
@property(nonatomic, copy) NSString * date;
@end

@interface PGNReadFileMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFilename:(NSString *)filename;
@property(nonatomic, copy) NSString * filename;
@end

@interface PGNFileResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSuccessful:(BOOL )successful
    error:(nullable NSString *)error
    response:(NSArray<PGNSaveQrScan *> *)response;
@property(nonatomic, assign) BOOL  successful;
@property(nonatomic, copy, nullable) NSString * error;
@property(nonatomic, copy) NSArray<PGNSaveQrScan *> * response;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *PGNGetMessagesCodec(void);

@protocol PGNDeviceFileApi
- (void)scanQRQr:(PGNSaveQrScan *)qr completion:(void (^)(PGNFileResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)readFileMsg:(PGNReadFileMessage *)msg completion:(void (^)(PGNFileResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpPGNDeviceFileApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNDeviceFileApi> *_Nullable api);

extern void SetUpPGNDeviceFileApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNDeviceFileApi> *_Nullable api, NSString *messageChannelSuffix);


@interface PGNFlutterFileApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)displayContentResponse:(PGNFileResponse *)response completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
