// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "QrScanPlugin.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PGNSaveQrScan ()
+ (PGNSaveQrScan *)fromList:(NSArray<id> *)list;
+ (nullable PGNSaveQrScan *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation PGNSaveQrScan
+ (instancetype)makeWithQrData:(NSString *)qrData
    date:(NSInteger )date {
  PGNSaveQrScan* pigeonResult = [[PGNSaveQrScan alloc] init];
  pigeonResult.qrData = qrData;
  pigeonResult.date = date;
  return pigeonResult;
}
+ (PGNSaveQrScan *)fromList:(NSArray<id> *)list {
  PGNSaveQrScan *pigeonResult = [[PGNSaveQrScan alloc] init];
  pigeonResult.qrData = GetNullableObjectAtIndex(list, 0);
  pigeonResult.date = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable PGNSaveQrScan *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNSaveQrScan fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.qrData ?: [NSNull null],
    @(self.date),
  ];
}
@end

@interface PGNQrScanPluginPigeonCodecReader : FlutterStandardReader
@end
@implementation PGNQrScanPluginPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [PGNSaveQrScan fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PGNQrScanPluginPigeonCodecWriter : FlutterStandardWriter
@end
@implementation PGNQrScanPluginPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PGNSaveQrScan class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PGNQrScanPluginPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PGNQrScanPluginPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PGNQrScanPluginPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PGNQrScanPluginPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PGNGetQrScanPluginCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PGNQrScanPluginPigeonCodecReaderWriter *readerWriter = [[PGNQrScanPluginPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpPGNQrApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNQrApi> *api) {
  SetUpPGNQrApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpPGNQrApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNQrApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.qr_scan_plugin_package.QrApi.setQrData", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetQrScanPluginCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setQrDataRequest:error:)], @"PGNQrApi api (%@) doesn't respond to @selector(setQrDataRequest:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        PGNSaveQrScan *arg_request = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setQrDataRequest:arg_request error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.qr_scan_plugin_package.QrApi.getListScan", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetQrScanPluginCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getListScanWithCompletion:)], @"PGNQrApi api (%@) doesn't respond to @selector(getListScanWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getListScanWithCompletion:^(NSArray<PGNSaveQrScan *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
