// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace pigeon_example {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class DeviceFileApi;
  friend class FlutterFileApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class SaveQrScan {
 public:
  // Constructs an object setting all fields.
  explicit SaveQrScan(
    const std::string& qr_data,
    const std::string& date);

  const std::string& qr_data() const;
  void set_qr_data(std::string_view value_arg);

  const std::string& date() const;
  void set_date(std::string_view value_arg);


 private:
  static SaveQrScan FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DeviceFileApi;
  friend class FlutterFileApi;
  friend class PigeonInternalCodecSerializer;
  std::string qr_data_;
  std::string date_;

};


// Generated class from Pigeon that represents data sent in messages.
class ReadFileMessage {
 public:
  // Constructs an object setting all fields.
  explicit ReadFileMessage(const std::string& filename);

  const std::string& filename() const;
  void set_filename(std::string_view value_arg);


 private:
  static ReadFileMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DeviceFileApi;
  friend class FlutterFileApi;
  friend class PigeonInternalCodecSerializer;
  std::string filename_;

};


// Generated class from Pigeon that represents data sent in messages.
class FileResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit FileResponse(
    bool successful,
    const flutter::EncodableList& response);

  // Constructs an object setting all fields.
  explicit FileResponse(
    bool successful,
    const std::string* error,
    const flutter::EncodableList& response);

  bool successful() const;
  void set_successful(bool value_arg);

  const std::string* error() const;
  void set_error(const std::string_view* value_arg);
  void set_error(std::string_view value_arg);

  const flutter::EncodableList& response() const;
  void set_response(const flutter::EncodableList& value_arg);


 private:
  static FileResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DeviceFileApi;
  friend class FlutterFileApi;
  friend class PigeonInternalCodecSerializer;
  bool successful_;
  std::optional<std::string> error_;
  flutter::EncodableList response_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class DeviceFileApi {
 public:
  DeviceFileApi(const DeviceFileApi&) = delete;
  DeviceFileApi& operator=(const DeviceFileApi&) = delete;
  virtual ~DeviceFileApi() {}
  virtual void ScanQR(
    const SaveQrScan& qr,
    std::function<void(ErrorOr<FileResponse> reply)> result) = 0;
  virtual void ReadFile(
    const ReadFileMessage& msg,
    std::function<void(ErrorOr<FileResponse> reply)> result) = 0;

  // The codec used by DeviceFileApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `DeviceFileApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    DeviceFileApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    DeviceFileApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  DeviceFileApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class FlutterFileApi {
 public:
  FlutterFileApi(flutter::BinaryMessenger* binary_messenger);
  FlutterFileApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void DisplayContent(
    const FileResponse& response,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace pigeon_example
#endif  // PIGEON_MESSAGES_G_H_
